#Advanced - Visualize Sales Team:
#- Advanced - Visualize Sales Team
#- https://towardsdatascience.com/how-to-explore-and-visualize-a-dataset-with-python-7da5024900ef
#- - Datascience
#  - BigData
#  - DataVisualization
#- How to visualize a data set!
Beginner - Install Anaconda:
- Beginner - Install Anaconda
- https://towardsdatascience.com/get-started-with-python-e50dc8c96589
- - Datascience
  - BigData
  - DataVisualization
  - Python
- Getting started with Python is easier than you think!
Advanced - Get Data From Sheets:
- Advanced - Get Data From Sheets
- https://towardsdatascience.com/replacing-sheets-with-python-f1608e58d2ca
- - Datascience
  - BigData
  - DataAnalytics
  - Python
- Pull data from Google Sheets programatically!
Advanced - Cohort Analysis:
- Advanced - Cohort Analysis
- https://medium.com/better-programming/cohort-analysis-with-python-e81d9d740a9b
- - Datascience
  - BigData
  - DataVisualization
  - Python
- Understand your customers retention!
#Advanced - @classmethod Decorator:
#- Advanced - @classmethod Decorator
#- https://medium.com/better-programming/use-the-little-known-classmethod-decorator-to-add-constructors-to-your-classes-464e96d8fe86
#- - Datascience
#  - BigData
#  - Programming
#  - Python
#- Use the classmethod decorator to add custom constructors!
Beginner - Master Pandas:
- Beginner - Master Pandas
- https://towardsdatascience.com/how-to-master-pandas-8514f33f00f6#14fd-ea883071854e
- - Datascience
  - BigData
  - DataAnalytics
  - Pandas
  - Python
- Learn how to master Pandas in 20 minutes
Advanced - Advanced Pandas:
- Advanced - Advanced Pandas
- https://towardsdatascience.com/learn-advanced-features-for-pythons-main-data-analysis-library-in-20-minutes-d0eedd90d086
- - Datascience
  - BigData
  - DataAnalytics
  - Pandas
  - Python
- Learn advanced Pandas feature in 20 minutes
Advanced - Image Scraping:
- Advanced - Image Scraping
- https://towardsdatascience.com/image-scraping-with-python-a96feda8af2d
- - Datascience
  - BigData
  - DataAnalytics
  - Pandas
  - Python
  - Automation
  - WebScraping
  - Bots
- Learn how to scrape images from Google
Advanced - Cat, Dog or Elon Musk:
- Advanced - Cat, Dog or Elon Musk
- https://towardsdatascience.com/cat-dog-or-elon-musk-145658489730
- - Datascience
  - BigData
  - DataAnalytics
  - Python
  - Automation
  - Machine Learning
  - Bots
- Learn how to build an image-recognizing convolutional neural network with Python and Keras in less than 15minutes!
Advanced - "transform" and "apply" to deal with missing values:
- Advanced - "transform" and "apply" to deal with missing values
- https://towardsdatascience.com/using-pandas-transform-and-apply-to-deal-with-missing-data-on-a-group-level-cb6ccf060531
- - Datascience
  - BigData
  - DataAnalytics
  - Python
  - Machine Learning
- Using Panda's "transform" and "apply" to deal with missing data on a group level
Advanced - Learn how to create beautiful and insightful charts with Python:
- Advanced - Learn how to create beautiful and insightful charts with Python
- https://towardsdatascience.com/plotting-with-python-c2561b8c0f1f
- - Datascience
  - DataVisualization
  - DataInsights
  - BigData
  - DataAnalytics
  - Python
  - Automation
  - Machine Learning
- Money can buy happiness. A comprehensive code-along guide to visualization with Python!
Beginners - Learn how to build a milestone referral program with ReactJS:
- Beginners - Learn how to build a milestone referral program with ReactJS
- https://medium.com/swlh/building-the-frontend-for-a-milestone-referral-program-2ccac1598894
- - JavaScript
  - ReactJS
  - WebDevelopment
  - SinglePageApp
  - FullStack
  - Bootstrap
  - Referral
- Check out this first part of a comprehensive code-along series to build your own fullstack app.